### ISSUE TITLE
Save_sample() error

### ISSUE THREAD

**Issue by djdarcy** [hlky/stable-diffusion-webui#107]
Small error on line 537 in webui.py. Doing txt-to-img with write sample info files tries to fill the `info_dict( ... seed = seed)`. It looks like you want to do `seed=seeds[i]`.

```Traceback (most recent call last):
  File "scripts/webui.py", line 321, in <module>
    model = load_model_from_config(config, "models/ldm/stable-diffusion-v1/model.ckpt")
  File "scripts/webui.py", line 102, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "c:\users\...\downloads\waifu-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\users\...\downloads\waifu-diffusion\ldm\models\diffusion\ddpm.py", line 448, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "c:\users\...\downloads\waifu-diffusion\ldm\models\diffusion\ddpm.py", line 86, in __init__
    self.model = DiffusionWrapper(unet_config, conditioning_key)
  File "c:\users\...\downloads\waifu-diffusion\ldm\models\diffusion\ddpm.py", line 1398, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
  File "c:\users\...\downloads\waifu-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\users\...\downloads\waifu-diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 598, in __init__
    ResBlock(
  File "c:\users\...\downloads\waifu-diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 230, in __init__
    conv_nd(dims, self.out_channels, self.out_channels, 3, padding=1)
  File "c:\users\...\downloads\waifu-diffusion\ldm\modules\diffusionmodules\util.py", line 225, in conv_nd
    return nn.Conv2d(*args, **kwargs)
  File "C:\app\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\conv.py", line 434, in __init__
    super(Conv2d, self).__init__(
  File "C:\app\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\conv.py", line 138, in __init__
    self.reset_parameters()
  File "C:\app\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\conv.py", line 144, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "C:\app\Anaconda3\envs\ldm\lib\site-packages\torch\nn\init.py", line 410, in kaiming_uniform_
    return tensor.uniform_(-bound, bound)```

**Comment by QuendirSkye** [comment]
Ah crap, didn't notice someone mentioned it already. Created a pr for it without taking a good look at the issues, heh.

**Comment by hlky** [comment]
#110
