### ISSUE TITLE
Error when using Img2Img Crop Edit

### ISSUE THREAD

**Issue by mediocreatmybest** [hlky/stable-diffusion-webui#124]
When trying to select using the crop edit method I get the following errors after clicking generate. 
Seems to be the only real issue I've had so far. Thanks 👍 

```
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

**Comment by hlky** [comment]
Possible duplicate #49 #65 

This should have been fixed, when did you update?

**Comment by mediocreatmybest** [comment]
Just rebuilt it then from https://github.com/hlky/stable-diffusion to make sure I was at the latest and then applied https://github.com/hlky/stable-diffusion-webui to test the latest version. 
So it looks like my https://github.com/hlky/stable-diffusion was the older version. 

but I am now getting a different error when trying to use crop. 


```
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\User\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 971, in img2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 466, in process_images
    grid_count = len([_ for x in os.listdir() if x.endswith(('.png', '.jpg'))]) - 1 # start at 0
  File "scripts/webui.py", line 466, in <listcomp>
    grid_count = len([_ for x in os.listdir() if x.endswith(('.png', '.jpg'))]) - 1 # start at 0
[MemMon] Recording max memory usage...
NameError: name '_' is not defined
```

If this is a duplicate happy to close it and open a new one if you prefer? 

Thanks!

**Comment by hlky** [comment]
The changes aren't merged yet, get only webui.py from this repo
