### ISSUE TITLE
[BUG] CUDA: Invalid device ordinal when using RealESRGAN

### ISSUE THREAD

**Issue by sazabidesu** [hlky/stable-diffusion-webui#159]
I keep getting this error:
`RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`
Whenever either I check "Upsacale images using RealESRGAN" on advanced tab, or when I use it on its dedicated tab. Everything else works flawlessly.

**Comment by hlky** [comment]
Probably related to --gpu

Windows? Linux? Do you have multiple graphics cards?

Was there more to that error, line number etc?

**Comment by sazabidesu** [comment]
Windows. 2 GPUs: 1080ti  / 1660ti 
I think that it is related to --gpu as I need it to force it to use my powerful gpu, or else it goes for the low performing one.

This is the full log after I execute it.
`Loaded RealESRGAN with model RealESRGAN_x4plus_anime_6B
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1284, in run_RealESRGAN
    output, img_mode = RealESRGAN.enhance(np.array(image, dtype=np.uint8))
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "x:\stablediffusion\stable-diffusion-main_2\src\realesrgan\realesrgan\utils.py", line 199, in enhance
    self.pre_process(img)
  File "x:\stablediffusion\stable-diffusion-main_2\src\realesrgan\realesrgan\utils.py", line 72, in pre_process
    self.img = img.unsqueeze(0).to(self.device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

**Comment by hlky** [comment]
Well are you using --gpu?

Which gpu is has which id?

show output from `nvidia-smi`

**Comment by sazabidesu** [comment]
Yes, I am using it as --gpu 1
If I don't, it tries to use the low performing GPU. 
This is nvidia-smi

![image](https://user-images.githubusercontent.com/112148372/187052276-673b4ecc-acd7-410c-b795-9cbb4b545c6f.png)

As you can see my second gpu has less vram. So I have to use --gpu 1 or else it wants to use that GPU.

**Comment by hlky** [comment]
Should be fixed
