### ISSUE TITLE
[BUG] Invalid URL 'yo': No schema supplied. Perhaps you meant http://yo?

### ISSUE THREAD

**Issue by SamuelArnold** [hlky/stable-diffusion-webui#270]
**Describe the bug**

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\gradio\processing_utils.py", line 35, in encode_url_or_file_to_base64
    requests.get(path)
  File "C:\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Python38\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Python38\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'yo': No schema supplied. Perhaps you meant http://yo?

**To Reproduce**
1. Go to '... realesgan tab'
2. Click on '.... generate button'

**Expected behavior**
Load Image

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser FIrefox

**Additional context**
I am not sure if put the webgui in the right place. Should be in ./SD or ./SD/SRC regardless It cant find "yo." The instructions should be clear where to extract it and what to run. and why. do you run webgui or webgui_playground etc.

**Comment by hlky** [comment]
@SamuelArnold you don't have to move it anywhere, you haven't [followed the instructions](https://github.com/hlky/stable-diffusion/wiki/Installation). You don't use this development branch unless you are a developer. Use the [main repo](https://github.com/hlky/stable-diffusion), you don't have to move anything.
