### ISSUE TITLE
[BUG] Assertion error with img2img

### ISSUE THREAD

**Issue by LuciferSam86** [hlky/stable-diffusion-webui#405]
**Describe the bug**
When using img2img I have an assertion error

**To Reproduce**
1. Go to "Stable diffusion image to image unified"
2. Load an image
3. Run it
4. I receive the error

**Expected behavior**
it should work

Here the stack
```
Traceback (most recent call last):
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\LuciferSam\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1288, in img2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 691, in process_images
    assert prompt is not None
AssertionError
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8456295/187799797-c7e98a60-9379-4583-bf9d-7263868b75ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Conda version : conda 4.14.0

**Additional context**
I'm using this SD fork : https://github.com/basujindal/stable-diffusion
and here the crossposted issue : https://github.com/basujindal/stable-diffusion/issues/95
but until yesterday it worked without problems. I tried even to download everything again and recreate the environment.
I followed this guide: https://rentry.org/GUItard

**Comment by codedealer** [comment]
It says that the prompt must not be empty.

**Comment by LuciferSam86** [comment]
and I'm a complete idiot with no sleep. Closing the issue :/
