### ISSUE TITLE
[BUG] Unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by mchaker** [hlky/stable-diffusion-webui#431]
**Describe the bug**
RealESRGAN fails to load with a message "got an unexpected keyword argument 'device'"

**To Reproduce**
1. clone repo
1. try running `relauncher.py`

**Expected behavior**
Startup with no errors

**Logs**

```
Relauncher: Launching...
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Loaded GFPGAN
Error loading RealESRGAN:
Traceback (most recent call last):
  File "webui.py", line 329, in try_loading_RealESRGAN
    RealESRGAN = load_RealESRGAN(model_name) # TODO: Should try to load both models before giving up
  File "webui.py", line 310, in load_RealESRGAN
    instance = RealESRGANer(scale=2, model_path=model_path, model=RealESRGAN_models[model_name], pre_pad=0, half=not opt.no_half, device=torch.device(f'cuda:{opt.gpu}'))
TypeError: __init__() got an unexpected keyword argument 'device'

Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
```

Specifically:

```
Error loading RealESRGAN:
Traceback (most recent call last):
  File "webui.py", line 329, in try_loading_RealESRGAN
    RealESRGAN = load_RealESRGAN(model_name) # TODO: Should try to load both models before giving up
  File "webui.py", line 310, in load_RealESRGAN
    instance = RealESRGANer(scale=2, model_path=model_path, model=RealESRGAN_models[model_name], pre_pad=0, half=not opt.no_half, device=torch.device(f'cuda:{opt.gpu}'))
TypeError: __init__() got an unexpected keyword argument 'device'
```

`stable-diffusion-webui` is running on a Linux server, accessed from my desktop machine.

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser chrome
 - Version 104

**Comment by hlky** [comment]
Update from main repo, upscalers have been moved to their own tab with batch support, this should eliminate any issues

**Comment by mchaker** [comment]
@hlky still receiving this error on startup.

```
Error loading RealESRGAN:
Traceback (most recent call last):
  File "webui.py", line 346, in try_loading_RealESRGAN
    RealESRGAN = load_RealESRGAN(model_name) # TODO: Should try to load both models before giving up
  File "webui.py", line 327, in load_RealESRGAN
    instance = RealESRGANer(scale=2, model_path=model_path, model=RealESRGAN_models[model_name], pre_pad=0, half=not opt.no_half, device=torch.device(f'cuda:{opt.gpu}'))
TypeError: __init__() got an unexpected keyword argument 'device'
```

I am running the webui via:
`python3 webui.py --no-half --precision=full --no-progressbar-hiding --gpu 0 --port 7860`

**Comment by hlky** [comment]
Well a few pointers to start

Enabling `--no-progressbar-hiding` option severely reduces performance so I don't know why you're using that

`--no-half --precision=full` are you sure you want to be running at full precision?

`--gpu 0` you don't need this unless the gpu you want to use isn't 0

`--port 7860`

**Comment by mchaker** [comment]
I'm using it on a server -- web browser is on a separate machine :)

full precision runs faster on my cards

i am running 3 instances of the UI - 1 instance for each card: port 7860, 8080, 8888 for gpu 0, 1, 2

and gpu 0 gets overloaded with python processes when the other instances (gpu 1 and 2) start

**Comment by mchaker** [comment]
@hlky when I use GPUs other than 0, it loads but then crashes when an image is requested:

```
Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**Comment by mchaker** [comment]
I also still get the error on RealESRGAN load mentioned in https://github.com/hlky/stable-diffusion-webui/issues/431#issuecomment-1234405468
