### ISSUE TITLE
[Bug]: Saving fails in Image Lab if --save-metadata is given

### ISSUE THREAD

**Issue by AbdBarho** [hlky/stable-diffusion-webui#456]
### What happened?

When using fix faces or upscale with RealESRGAN from the (new) Image Lab, the generation of the image succeeds, but saving it fails because saving the metadata fails because the prompt is missing.

Running without `--save-metadata` works fine.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
--outdir /output --ckpt /models/model.ckpt --ldsr-dir /latent-diffusion --save-metadata --optimized
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1721, in imgproc
    save_sample(image, outpathDir, outFilename, False, None, None, None, None, None, None, None, None, None, None, None, None, None, False, None, None, None, None, None, None, None, None, None)  
  File "scripts/webui.py", line 572, in save_sample
    metadata.add_text("SD:prompt", prompts[i])
TypeError: 'NoneType' object is not subscriptable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

BTW. Nice bug template!

**Comment by hlky** [comment]
Fixed, no metadata except for GoBIG anyway which can be added in another commit, existing metadata could be read and preserved on new file.
