### ISSUE TITLE
[Bug]: img2img() missing 1 required positional argument: 'fp'

### ISSUE THREAD

**Issue by HenkDz** [hlky/stable-diffusion-webui#463]
### What happened?

A bug happened! 
After updating to the latest version (which is great) a new bug emerged. When you mask and try to generate img2img you see this error.

![image](https://user-images.githubusercontent.com/17301927/187996352-bf709a12-cfc0-4659-bd47-74092fc54f9b.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "E:\a3\envs\ldm\lib\site-packages\gradio\routes.py", line 248, in run_predict
    output = await app.blocks.process_api(
  File "E:\a3\envs\ldm\lib\site-packages\gradio\blocks.py", line 643, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "E:\a3\envs\ldm\lib\site-packages\gradio\blocks.py", line 558, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\a3\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\a3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\a3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: img2img() missing 1 required positional argument: 'fp'
Traceback (most recent call last):
  File "E:\a3\envs\ldm\lib\site-packages\gradio\routes.py", line 248, in run_predict
    output = await app.blocks.process_api(
  File "E:\a3\envs\ldm\lib\site-packages\gradio\blocks.py", line 643, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "E:\a3\envs\ldm\lib\site-packages\gradio\blocks.py", line 558, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\a3\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\a3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\a3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: img2img() missing 1 required positional argument: 'fp'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudumaroja** [comment]
i have the same problem with img2img.. 

i have a gtx 1660 ti (6gb) so i use the extra commands

python scripts/webui.py --no-half --precision=full --optimized

i dont know if this information helps.. but more information wont hurt.

**Comment by fload** [comment]
I believe the problem is on line 1139 in webui.py, quick fix might be setting a default of fp = None

**Comment by croquelois** [comment]
yeah, just reverted the line 215-217 and 291 and 300 in https://github.com/hlky/stable-diffusion-webui/commit/decd31ca92ae51e6f3440f4101a6ca5ab759c256 and it work again

**Comment by codedealer** [comment]
img2img_batch_size was removed recklessly

**Comment by rrweller** [comment]
> croquelois

can confirm this fixed it for me as well

**Comment by HenkDz** [comment]
> I reverted the line 215-217 and 291 and 300 in [decd31c](https://github.com/hlky/stable-diffusion-webui/commit/decd31ca92ae51e6f3440f4101a6ca5ab759c256) and it work again

Does it need this as well? @hlky

**Comment by HenkDz** [comment]
it introduced this 

![image](https://user-images.githubusercontent.com/17301927/188013679-ea75c437-0a23-476f-9000-ed66146d7e2c.png)

**Comment by hlky** [comment]
@croquelois all of img2img_batch_size was not removed properly, sorry about that
