### ISSUE TITLE
[Bug]: gobig "IndexError: list index out of range"

### ISSUE THREAD

**Issue by darthdeus** [hlky/stable-diffusion-webui#464]
### What happened?

When I run upscale with `GoBig` I get the following error

Running on latest version from `main` at commit 70bd4a4c21983292d3b396efaa026d6820869581

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1729, in imgproc
    image = processGoBig(image)
  File "scripts/webui.py", line 1663, in processGoBig
    work_results.append(output_images[0])
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment]
Thanks, taking a look.

**Comment by HenkDz** [comment]
facing the same.

![image](https://user-images.githubusercontent.com/17301927/188017826-b887af85-5aff-45e4-b930-a00c5f2e7f9a.png)

**Comment by devilismyfriend** [comment]
Fixed in the latest PR, thanks for reporting.

**Comment by caacoe** [comment]
![image](https://user-images.githubusercontent.com/110500565/188241493-d22ef3d1-9a14-407d-8174-04646bd6df52.png)

Just updated to the latest, appears to provide me a slightly different error? Non 'gobig' upscaling options are fine

**Comment by Yrbashazar** [comment]
![Screenshot_2022-09-03-00-14-52-415_com.google.chromeremotedesktop.jpg](https://user-images.githubusercontent.com/110055383/188241714-1695f898-b5bd-4a1d-9455-f01d6f3f7078.jpg)
