### ISSUE TITLE
[Bug]: img2img() missing 1 required positional argument: 'fp'

### ISSUE THREAD

**Issue by darthdeus** [hlky/stable-diffusion-webui#466]
### What happened?

Just opened the img2img tab and clicked "generate", seems to happen no matter what settings.

Running from stable repo on commit 70bd4a4c21983292d3b396efaa026d6820869581.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "c:\dev\tools\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: img2img() missing 1 required positional argument: 'fp'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by croquelois** [comment]
https://github.com/hlky/stable-diffusion-webui/issues/463

**Comment by Guizmus** [comment]
I made a duplicate in https://github.com/hlky/stable-diffusion-webui/issues/470 too, sorry

**Comment by hlky** [comment]
Fixed, sorry.
