### ISSUE TITLE
[Bug]: img2img() missing 1 required positional argument: 'fp'

### ISSUE THREAD

**Issue by croon** [hlky/stable-diffusion-webui#467]
### What happened?

When using "Image-to-Image Unified" in the web UI, uploading an image, specifying a prompt, leaving everything else as default, the generation fails, and the console spits out the following error:

Traceback (most recent call last):
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: img2img() missing 1 required positional argument: 'fp'

Text-to-Image works normally. Image-to-Image worked on a previous commit, I unfortunately don't know specifically which. I also tried deleting the entire directory, cloning the repo again, deleting my conda environment in my profile and letting the repo recreate the environment.

One further thing to note is that during startup, the console also states this:
C:\Users\<username>\.conda\envs\ldo\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(

If it pertains to this I'm unsure.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\<username>\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: img2img() missing 1 required positional argument: 'fp'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by croquelois** [comment]
https://github.com/hlky/stable-diffusion-webui/issues/463

**Comment by croon** [comment]
Sorry, it must have been reported while I was writing mine. Thanks.
