### ISSUE TITLE
[Bug]: img2img with resizing : img2img() missing 1 required positional argument: 'fp'

### ISSUE THREAD

**Issue by Guizmus** [hlky/stable-diffusion-webui#470]
### What happened?

While using the same test case as in this previous issue : https://github.com/hlky/stable-diffusion/issues/200
I now have this error message :
![image](https://user-images.githubusercontent.com/1162494/188012913-3a05c52d-1167-47e3-8ff7-d30a72d17df7.png)
test done after the commit fbf814ebdff6ab08a56b87de947193e602a7918a

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\berti\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\berti\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\berti\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\berti\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\berti\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\berti\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: img2img() missing 1 required positional argument: 'fp'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Guizmus** [comment]
I'm sorry, I didn't see the new bug tracker, this is a duplicate, I'll link it to https://github.com/hlky/stable-diffusion-webui/issues/466
