### ISSUE TITLE
[Bug]: GoBIG index error (Out Of Range)

### ISSUE THREAD

**Issue by Ehplodor** [hlky/stable-diffusion-webui#508]
### What happened?

Running GoBIG or GoLATENT : index out of range after first iteration

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Processing images...
Unloaded GFPGAN
Loaded RealESGAN
GoBig upscaling will process a total of 9 images tiled as 3x3 in a total of 9 batches.
[MemMon] Recording max memory usage...

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  2.46it/s]
[MemMon] Stopped recording.

Traceback (most recent call last):
  File "C:\Users\hades\anaconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\hades\anaconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\hades\anaconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\hades\anaconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\hades\anaconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hades\anaconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1731, in imgproc
    image = processGoBig(image)
  File "scripts/webui.py", line 1665, in processGoBig
    work_results.append(output_images[0])
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ehplodor** [comment]
Seems already fixed in an upcoming PR

**Comment by Ehplodor** [comment]
Seems already fixed in an upcoming PR
