### ISSUE TITLE
[Bug]: list index out of range on clean install when pushing to Image lab and performing GoBig upscale

### ISSUE THREAD

**Issue by MofoMojo** [hlky/stable-diffusion-webui#519]
### What happened?

Clean install, no changes. 
Generate an image in the TXT-To-Image tab. Once image is generate select Send to Lab option
Image shows up in the Image Lab tab, select the Upscale checkbox 
In Upscale settings enable GoBig radial
Select Process Button

The first iteration appears to complete, and then you get an error that ends with
IndexError: list index out of range

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Where are you running the webui?

Windows

### Relevant log output

```shell
Processing images...
Loaded RealESGAN
GoBig upscaling will process a total of 9 images tiled as 3x3 in a total of 9 batches.
[MemMon] Recording max memory usage...

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  7.54it/s]
Traceback (most recent call last):
  File "C:\Users\stuar\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\stuar\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\stuar\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\stuar\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\stuar\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\stuar\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1731, in imgproc
    image = processGoBig(image)
  File "scripts/webui.py", line 1665, in processGoBig
    work_results.append(output_images[0])
IndexError: list index out of range
[MemMon] Stopped recording.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MofoMojo** [comment]
See this has been filed before and may be fixed in upcoming PR. Closing. My mistake, I thought I searched first.
