### ISSUE TITLE
[Bug]: UI fails on prompts longer than 128 characters

### ISSUE THREAD

**Issue by DefaultAlias** [hlky/stable-diffusion-webui#537]
### What happened?

Creating any prompts over 128 characters long causes a FileNotFoundError exception, as the script can't create a folder with a name longer than that for some reason. A folder -is- created by only up to the first 128 characters of the prompt. 

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
[MemMon] Recording max memory usage...

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:06<00:00,  7.28it/s]
Traceback (most recent call last):
  File "C:\Users\Logan\.conda\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Logan\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\Logan\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Logan\.conda\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Logan\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Logan\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 998, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 896, in process_images
    save_sample(image, sample_path_i, filename, jpg_sample, prompts, seeds, width, height, steps, cfg_scale,
  File "scripts/webui.py", line 544, in save_sample
    image.save(f"{filename_i}.png")
  File "C:\Users\Logan\.conda\envs\ldm\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/txt2img-samples\\samples\\something_that_is_something_that_is_something_that_is_something_that_is_something_that_is_something_that_is_something_that_is_so\\00000-50_k_lms_3995315836.png'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment]
If I'm not mistaken the 128 limit is a windows thing, perhaps we should add a check for it and shorten it on demand.

**Comment by hlky** [comment]
This is not a bug, the paths are already truncated to avoid hitting the path limit.
If you are, I would suggest moving entire stable-diffusion folder to a shorter path, alternatively just don't use the save by prompt option.
