### ISSUE TITLE
[Bug]: "List Index out of Range" when trying to upscale with GOBIG

### ISSUE THREAD

**Issue by OblivionDawn** [hlky/stable-diffusion-webui#546]
### What happened?

When trying to upscale with GOBIG, I get a Python error after the first image is rendered.

Here's the error:

```
Traceback (most recent call last):
  File "C:\Users\obliv\anaconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\obliv\anaconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\obliv\anaconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\obliv\anaconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\obliv\anaconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\obliv\anaconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1731, in imgproc
    image = processGoBig(image)
  File "scripts/webui.py", line 1665, in processGoBig
    work_results.append(output_images[0])
IndexError: list index out of range
```

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by altryne** [comment]
https://github.com/hlky/stable-diffusion-webui/pull/473 WIP
