### ISSUE TITLE
[Bug]: Grid fails to generate when "Fix faces using GFPGAN" is selected (divide by zero error)

### ISSUE THREAD

**Issue by Chito-Chito-Chito** [hlky/stable-diffusion-webui#551]
### What happened?

When generating with the "Fix faces using GPFGAN" option selected, the grid does not generate, no images are loaded into the webui, and a console message ending with a divide by zero error is shown.  The actual individual images do generate.  I've tried this on chrome and brave browsers, and several installs.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\Name\miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Name\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\Name\miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Name\miniconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Name\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Name\miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1053, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 969, in process_images
    grid = image_grid(output_images, batch_size)
  File "scripts/webui.py", line 456, in image_grid
    cols = math.ceil(len(imgs) / rows)
ZeroDivisionError: division by zero
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chito-Chito-Chito** [comment]
Dupe of #516; apologies (I didn't look in the webui repo issues section first).
