### ISSUE TITLE
[Bug]: No usable font found error

### ISSUE THREAD

**Issue by Gushousekai195** [hlky/stable-diffusion-webui#552]
### What happened?

When using the application, when I try to generate something it returns an error “No usable font found.” It wasn’t doing this before today.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Safari

### Where are you running the webui?

Colab

### Relevant log output

```shell
Iteration: 1/1
100% 50/50 [00:19<00:00,  2.58it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 998, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 923, in process_images
    grid = image_grid(output_images, batch_size)
  File "scripts/webui.py", line 419, in image_grid
    fnt = get_font(30)
  File "scripts/webui.py", line 401, in get_font
    raise Exception(f"No usable font found (tried {', '.join(fonts)})")
Exception: No usable font found (tried arial.ttf, DejaVuSans.ttf)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
> Colab

This is Colab related issue. Nothing has changed with fonts in the code since yesterday.

**Comment by Jay4242** [comment]
Not sure the arial.ttf was being downloaded correctly, I redid:
%cd /content/stable-diffusion/
!wget https://github.com/matomo-org/travis-scripts/blob/master/fonts/Arial.ttf?raw=true -O arial.ttf
and it started working.
