### ISSUE TITLE
[Bug]: No usable font found error

### ISSUE THREAD

**Issue by sinsiuwo** [hlky/stable-diffusion-webui#554]
### What happened?

When using the application, when I try to generate something it returns an error “No usable font found.”

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Where are you running the webui?

Colab

### Relevant log output

```shell
Iteration: 1/1
100% 38/38 [00:11<00:00,  3.25it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/usr/local/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1279, in img2img
    grid = image_grid(history, batch_size, force_n_rows=1)
  File "scripts/webui.py", line 419, in image_grid
    fnt = get_font(30)
  File "scripts/webui.py", line 401, in get_font
    raise Exception(f"No usable font found (tried {', '.join(fonts)})")
Exception: No usable font found (tried arial.ttf, DejaVuSans.ttf)
[MemMon] Stopped recording.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
#552 
Duplicate.
Not a bug.
