### ISSUE TITLE
[Bug]: Img2Img crashes if DDIM sampler is used

### ISSUE THREAD

**Issue by AbdBarho** [hlky/stable-diffusion-webui#559]
### What happened?

Img2Img crashes if DDIM sampler is used. All other samplers work fine.

Steps to reproduce:
* open ui
* go to Image-to-Image Unified
* insert prompt: a fantasy landscape, artstation, vector graphics
* change sampler to DDIM
* click generate

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
python3 -u scripts/webui.py --outdir /output --ckpt /models/model.ckpt --ldsr-dir /latent-diffusion --save-metadata --extra-models-cpu --optimized-turbo
```

### Relevant log output

```shell
Exception processing job JobInfo(inputs=('a fantasy landscape, artstation, vector graphics', 'Crop', <PIL.Image.Image image mode=RGBA 
size=1024x512 at 0x7F607D0E6BE0>, 0, 3, 5, 'DDIM', [1, 4, 5, 6, 7], 'RealESRGAN_x4plus', 2, 5, 0.75, None, 512, 512, 0, None), func=<function img2img at 0x7f61001ea550>, session_key='"71bf0f574d264afa805ac676e1552634"', job_token=0, images=[], should_stop=<threading.Event object at 0x7f607d0e6cd0>, job_status="Error: decode() got an unexpected keyword argument 'z_mask'", finished=False, removed_output_idxs=[0]): decode() got an unexpected keyword argument 'z_mask'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 611, in postprocess_data
    block.postprocess(prediction_value)
  File "/opt/conda/lib/python3.8/site-packages/gradio/components.py", line 673, in postprocess
    return self.round_to_precision(y, self.precision)
  File "/opt/conda/lib/python3.8/site-packages/gradio/components.py", line 563, in round_to_precision
    return float(num)
ValueError: could not convert string to float: 'aea73d6ac1584a7daeb4a8aee0762371'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by astanziola** [comment]
I have the same issue also with other samples if I mask a part of the image.

**Comment by iChristGit** [comment]
I have the issue, no matter the sampler

**Comment by Theagainmen** [comment]
I think I've installed this repo around 3 days ago, which I think was maybe right before this fix! How do I exactly update the repo without installing everything again?
