### ISSUE TITLE
Exception when trying to use img2img

### ISSUE THREAD

**Issue by JohannesGaessler** [hlky/stable-diffusion-webui#56]
To reproduce:

1. Launch script.
2. Open in web browser, switch to img2img tab.
3. Type in any random prompt without touching anything else.
4. Press "Generate" button.

This results in the following exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/usr/lib/python3.10/site-packages/gradio/blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "/usr/lib/python3.10/site-packages/gradio/blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "/usr/lib/python3.10/site-packages/gradio/components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

Manifestation is different when using this PR https://github.com/hlky/stable-diffusion-webui/pull/29 but the effect and steps to reproduce are the same.

**Comment by hlky** [comment]
Duplicate #49
