### ISSUE TITLE
[Bug]: It appears as though Image2Image is now broken when selecting the Mask Option

### ISSUE THREAD

**Issue by Kuhlio** [hlky/stable-diffusion-webui#565]
### What happened?

Image 2 Image seems to work fine under Crop mode; however, when selecting Mask mode and running, an error gets thrown.  I have copied screen output into "Relevant log output" section below.

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Relevant log output

```shell
Exception processing job JobInfo(inputs=('test', 'Mask', <PIL.Image.Image image mode=RGBA size=1024x512 at 0x1A2A9272850>, 0, 3, 50, 'k_lms', [1, 4, 5, 6, 7], 'RealESRGAN_x4plus', 1, 5, 0.75, None, 512, 512, 0, None), func=<function img2img at 0x000001A2A4547280>, session_key='"4cb08b0313b84bf8a1a887c8a9448547"', job_token=0, images=[], should_stop=<threading.Event object at 0x000001A2A9272040>, job_status="Error: 'Image' object is not subscriptable", finished=False, removed_output_idxs=[0]): 'Image' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\k\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\k\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "C:\Users\k\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 611, in postprocess_data
    block.postprocess(prediction_value)
  File "C:\Users\k\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 673, in postprocess
    return self.round_to_precision(y, self.precision)
  File "C:\Users\k\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 563, in round_to_precision
    return float(num)
ValueError: could not convert string to float: 'ac97b61c951445dcb3027961816245fb'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbdBarho** [comment]
Related #559

**Comment by HenkDz** [comment]
Has this been fixed?
