### ISSUE TITLE
[Bug]: superResolution() takes 2 positional arguments but 5 were given

### ISSUE THREAD

**Issue by DenkingOfficial** [hlky/stable-diffusion-webui#573]
### What happened?

Error while using GoLatent or Latent Diffusion SR Upscale Mode
`TypeError: superResolution() takes 2 positional arguments but 5 were given`

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
--optimized-turbo, --share
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1839, in imgproc
    image = processLDSR(image)
  File "scripts/webui.py", line 1766, in processLDSR
    result = LDSR.superResolution(image,int(imgproc_ldsr_steps),str(imgproc_ldsr_pre_downSample),str(imgproc_ldsr_post_downSample))
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Software\Programming\Miniconda\envs\ldo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: superResolution() takes 2 positional arguments but 5 were given
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DenkingOfficial** [comment]
Thank you so much!
