### ISSUE TITLE
[Bug]: GoLatent upscaler has a syntax error

### ISSUE THREAD

**Issue by extesy** [hlky/stable-diffusion-webui#580]
### What happened?

When using GoLatent upscaler, it hits a syntax error after loading LDSR model: `superResolution() takes 2 positional arguments but 5 were given`

### Version

0.0.1 (Default)

### Relevant log output

```shell
Loaded LDSR
Traceback (most recent call last):
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1868, in imgproc
    image = processLDSR(image)
  File "scripts/webui.py", line 1783, in processLDSR
    result = LDSR.superResolution(image,int(imgproc_ldsr_steps),str(imgproc_ldsr_pre_downSample),str(imgproc_ldsr_post_downSample))
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\olega\anaconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: superResolution() takes 2 positional arguments but 5 were given
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by extesy** [comment]
Apparently I need to manually update https://github.com/devilismyfriend/latent-diffusion because it's not updated automatically.
