### ISSUE TITLE
[Bug]: Update breaks crop functionality of img2img.

### ISSUE THREAD

**Issue by astrorut** [hlky/stable-diffusion-webui#613]
### What happened?

one of the latest updates breaks img2img and produces an error on attempting to generate an image. This does not occur when using the mask tool, only the crop tool. It is incredibly inconvienient to have to try to masak the whole image every time to get img2img to work.

the following error outputs to the terminal after generate is clicked

Traceback (most recent call last):
  File "/home/user/.conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/.conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "/home/user/.conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "/home/user/.conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HenkDz** [comment]
I can confirm the issue of "string indices must be integers" in img2img tab

**Comment by hlky** [comment]
See #610 

Switch to mask, switch back to crop

Also test https://github.com/hlky/stable-diffusion-webui/tree/img2img-fix

Closing, discussion of this issue will continue in #610
