### ISSUE TITLE
"string indices must be integers" when running image 2 image on default settings

### ISSUE THREAD

**Issue by santagada** [hlky/stable-diffusion-webui#65]
Trying to use image-to-image tab in webui if you try to use the Editor mode crop which is the default this is the error you get:

```
Traceback (most recent call last):
  File "Miniconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 248, in run_predict
    output = await app.blocks.process_api(
  File "Miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "Miniconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 545, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "Miniconda3\envs\ldm\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

Looking a bit deeper seems to be the one of the image editors from gradio is in "sketch" tool mode but the data it has is just the name of the file, that is part of "select" mode

**Comment by oldfndm** [comment]
Did you update to the last commit? It should be fixed

**Comment by hlky** [comment]
This should be fixed, update

**Comment by feelie75** [comment]
I am also getting this error and I JUST download the .ZIP only 1 hour ago, so I assume that's the newest version, right?
