### ISSUE TITLE
[Bug]: Linux Install Script - module 'jinja2' has no attribute 'contextfunction'

### ISSUE THREAD

**Issue by fenixstarlord** [hlky/stable-diffusion-webui#661]
### What happened?

After running the install scrip succefully, when the script goes to launch, I get the following error - 

AttributeError: module 'jinja2' has no attribute 'contextfunction'
Relauncher: Process is ending. Relaunching in 1s...

### Version

0.0.1 (Default)

### Where are you running the webui?

Linux

### Relevant log output

```shell
########## CUSTOMIZE LAUNCH ARGUMENTS ##########

Do you wish to customize the launch arguments for Ultimate Stable Diffusion?
(This will be where you select Optimized mode, auto open in browser, share to public, and more.)
1) Yes
2) No
#? 2
Maintaining current launch arguments...
Running linux-setup.sh...
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
  File "/home/chris/stablediffusion/ultimate-stable-diffusion/frontend/frontend.py", line 1, in <module>
    import gradio as gr
  File "/home/chris/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/chris/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/components.py", line 39, in <module>
    from gradio.blocks import Block
  File "/home/chris/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 19, in <module>
    from gradio import (
  File "/home/chris/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/networking.py", line 18, in <module>
    from gradio.routes import App
  File "/home/chris/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/routes.py", line 48, in <module>
    templates = Jinja2Templates(directory=STATIC_TEMPLATE_LIB)
  File "/home/chris/.local/lib/python3.8/site-packages/starlette/templating.py", line 53, in __init__
    self.env = self.get_env(directory)
  File "/home/chris/.local/lib/python3.8/site-packages/starlette/templating.py", line 56, in get_env
    @jinja2.contextfunction
AttributeError: module 'jinja2' has no attribute 'contextfunction'
Relauncher: Process is ending. Relaunching in 1s...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chris-aeviator** [comment]
how was this solved?
