### ISSUE TITLE
[Bug]: Image2Image Crop + Uncrop broken

### ISSUE THREAD

**Issue by Sharrnah** [hlky/stable-diffusion-webui#667]
### What happened?

Since some time, Image2Image is broken when i try to use its Crop + Uncrop Functions.
I get the following error in the console:
```
stablediffusion  | Traceback (most recent call last):
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
stablediffusion  |     output = await app.blocks.process_api(
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
stablediffusion  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
stablediffusion  |     processed_input.append(block.preprocess(raw_input[i]))
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1546, in preprocess
stablediffusion  |     x, mask = x["image"], x["mask"]
stablediffusion  | TypeError: string indices must be integers
```

It worked a while ago.

Mask feature is working without errors.

Running it inside Docker. Just pulled and rebuild image a couple minutes ago.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Where are you running the webui?

Linux

### Custom settings

```shell
--precision full --precision=full --no-half
```

### Relevant log output

```shell
stablediffusion  | Traceback (most recent call last):
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
stablediffusion  |     output = await app.blocks.process_api(
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
stablediffusion  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
stablediffusion  |     processed_input.append(block.preprocess(raw_input[i]))
stablediffusion  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1546, in preprocess
stablediffusion  |     x, mask = x["image"], x["mask"]
stablediffusion  | TypeError: string indices must be integers
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sharrnah** [comment]
Oops. probably duplicate of https://github.com/hlky/stable-diffusion-webui/issues/632 and https://github.com/hlky/stable-diffusion-webui/issues/610

can be closed then.
