### ISSUE TITLE
webui.py fails with NameError: name '_' is not defined on line 466

### ISSUE THREAD

**Issue by altryne** [hlky/stable-diffusion-webui#99]
_ should be x 
```
Traceback (most recent call last):
  File "C:\Users\micro\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 248, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\micro\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 643, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\micro\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 558, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\micro\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\micro\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\micro\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "c:\Users\micro\projects\sd\webui-2.py", line 736, in txt2img
    output_images, seed, info, stats = process_images(
  File "c:\Users\micro\projects\sd\webui-2.py", line 466, in process_images
    grid_count = len([_ for x in os.listdir() if x.endswith(('.png', '.jpg'))]) - 1 # start at 0
  File "c:\Users\micro\projects\sd\webui-2.py", line 466, in <listcomp>
    grid_count = len([_ for x in os.listdir() if x.endswith(('.png', '.jpg'))]) - 1 # start at 0
NameError: name '_' is not defined
```

**Comment by altryne** [comment]
Looks like the same _ exists in other places, replacing with x works locally (I can prob. open a PR?)

**Comment by hlky** [comment]
fixed
